apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2023-08-31T17:32:06Z"
  name: stats-api
  namespace: todo-app-3
  resourceVersion: "40123160"
  uid: c402a84f-5dd6-4bba-85e6-42c593f46019
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stats-api
status:
  conditions:
  - lastTransitionTime: "2023-08-31T17:32:21Z"
    message: the HPA controller was able to get the target's current scale
    reason: SucceededGetScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2023-08-31T17:32:36Z"
    message: 'the HPA was unable to compute the replica count: failed to get cpu utilization:
      missing request for cpu'
    reason: FailedGetResourceMetric
    status: "False"
    type: ScalingActive
  currentMetrics: null
  currentReplicas: 2
  desiredReplicas: 2
  lastScaleTime: "2023-08-31T17:32:21Z"
