parameters:
  - name: TelemetryKind
    displayName: Telemetry Type so that correct application insights key is selected
    default: "TELEMETRY_DEVELOPMENT"
    values:
      - TELEMETRY_DEVELOPMENT
      - TELEMETRY_STAGING
      - TELEMETRY_PRODUCTION
  - name: BuildConfiguration
    displayName: BuildConfiguration to be used
    default: "Release"
    values:
      - Release
      - Debug

variables:
- name: BuildParameters.dotnetversion
  value: 7.0.x
- name: BuildParameters.dotnetversionforbuild
  value: net7.0
- name: BuildParameters.nugetversion
  value: 5.9.x
- name: TeamName
  value: Mindaro
- name: RunTests
  value: "true"
  

trigger: none
name: $(date:yyyyMMdd)$(rev:.r)

jobs:
  - job: Build
    strategy:
      matrix:
        win-x64-sf:
          BuildPlatform: "win-x64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/windows/amd64/kubectl.exe"
          KubectlPath: "win"
          KubectlFileName: "kubectl.exe"
          ZipFilePathName: "win"
          ZipFileName: "lpk-win.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        win-arm64-sf:
          BuildPlatform: "win-arm64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/windows/arm64/kubectl.exe"
          KubectlPath: "win"
          KubectlFileName: "kubectl.exe"
          ZipFilePathName: "win"
          ZipFileName: "lpk-win.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        linux-x64-sf:
          BuildPlatform: "linux-x64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
          KubectlPath: "linux"
          KubectlFileName: "kubectl"
          ZipFilePathName: "linux"
          ZipFileName: "lpk-linux.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        linux-arm64-sf:
          BuildPlatform: "linux-arm64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/linux/arm64/kubectl"
          KubectlPath: "linux"
          KubectlFileName: "kubectl"
          ZipFilePathName: "linux"
          ZipFileName: "lpk-linux.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        osx-x64-sf:
          BuildPlatform: "osx-x64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/darwin/amd64/kubectl"
          KubectlPath: "osx"
          KubectlFileName: "kubectl"
          ZipFilePathName: "osx"
          ZipFileName: "lpk-osx.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        osx-arm64-sf:
          BuildPlatform: "osx-arm64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/darwin/arm64/kubectl"
          KubectlPath: "osx"
          KubectlFileName: "kubectl"
          ZipFilePathName: "osx"
          ZipFileName: "lpk-osx.zip"
          vmImage: "macos-13-arm64"
    pool:
      name: $(poolName)
      vmImage: $(vmImage)
    steps:
      - template: templates/build.yml
        parameters:
          TelemetryKind: ${{ parameters.TelemetryKind }}
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          BuildPlatform: $(BuildPlatform)
          SelfContained: $(SelfContained)
          KubectlDownloadUrl: $(KubectlDownloadUrl)
          KubectlPath: $(KubectlPath)
          KubectlFileName: $(KubectlFileName)
          ZipFilePathName: $(ZipFilePathName)
          ZipFileName: $(ZipFileName)
      - template: templates/generate-lks.yml
