parameters:
  - name: TelemetryKind
    displayName: Telemetry Type so that correct application insights key is selected
    default: "TELEMETRY_DEVELOPMENT"
    values:
      - TELEMETRY_DEVELOPMENT
      - TELEMETRY_STAGING
      - TELEMETRY_PRODUCTION
  - name: BuildConfiguration
    displayName: BuildConfiguration to be used
    default: "Release"
    values:
      - Release
      - Debug
  - name: BuildPlatform
    displayName: BuildPlatform to be used
    default: "win-x64"
    values:
      - win-x64
      - win-arm64
  - name: SelfContained
    displayName: SelfContained to be used
    default: "true"
    values:
      - "true"
      - "false"
  - name: KubectlDownloadUrl
    displayName: KubectlDownloadUrl to be used
    default: "https://dl.k8s.io/release/v1.27.3/bin/windows/amd64/kubectl.exe"
  - name: KubectlPath
    displayName: KubectlPath to be used
    default: "win"
  - name: KubectlFileName
    displayName: KubectlFileName to be used
    default: "kubectl.exe"
  - name: ZipFilePathName
    displayName: ZipFilePathName to be used
    default: "win"
  - name: ZipFileName
    displayName: ZipFileName to be used
    default: "lpk-win.zip"

variables:
- name: BuildParameters.dotnetversion
  value: 7.0.x
- name: BuildParameters.dotnetversionforbuild
  value: net7.0
- name: BuildParameters.nugetversion
  value: 5.9.x
- name: TeamName
  value: Mindaro
- name: RunTests
  value: "true"
  

trigger: none
name: $(date:yyyyMMdd)$(rev:.r)

jobs:
  - job: Build
    strategy:
      matrix:
        win-x64-sf:
          TelemetryKind: ${{ parameters.TelemetryKind }}
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          BuildPlatform: "win-x64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/windows/amd64/kubectl.exe"
          KubectlPath: "win"
          KubectlFileName: "kubectl.exe"
          ZipFilePathName: "win"
          ZipFileName: "lpk-win.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        win-arm64-sf:
          TelemetryKind: ${{ parameters.TelemetryKind }}
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          BuildPlatform: "win-arm64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/windows/arm64/kubectl.exe"
          KubectlPath: "win"
          KubectlFileName: "kubectl.exe"
          ZipFilePathName: "win"
          ZipFileName: "lpk-win.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        linux-x64-sf:
          TelemetryKind: ${{ parameters.TelemetryKind }}
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          BuildPlatform: "linux-x64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
          KubectlPath: "linux"
          KubectlFileName: "kubectl"
          ZipFilePathName: "linux"
          ZipFileName: "lpk-linux.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        linux-arm64-sf:
          TelemetryKind: ${{ parameters.TelemetryKind }}
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          BuildPlatform: "linux-arm64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/linux/arm64/kubectl"
          KubectlPath: "linux"
          KubectlFileName: "kubectl"
          ZipFilePathName: "linux"
          ZipFileName: "lpk-linux.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
    pool:
      name: $(poolName)
      demands:
        - msbuild
        - visualstudio
        - DotNetFramework
      vmImage: $(vmImage)
    steps:
      - template: templates/build.yml
        parameters:
          TelemetryKind: ${{ parameters.TelemetryKind }}
          BuildConfiguration: ${{ parameters.BuildConfiguration }}
          BuildPlatform: ${{ parameters.BuildPlatform }}
          SelfContained: ${{ parameters.SelfContained }}
          KubectlDownloadUrl: ${{ parameters.KubectlDownloadUrl }}
          KubectlPath: ${{ parameters.KubectlPath }}
          KubectlFileName: ${{ parameters.KubectlFileName }}
          ZipFilePathName: ${{ parameters.ZipFilePathName }}
          ZipFileName: ${{ parameters.ZipFileName }}
      - template: templates/generate-lks.yml
