parameters:
  - name: TelemetryType
    displayName: Telemetry Type so that correct application insights key is selected
    default: "TELEMETRY_DEVELOPMENT"
    values:
      - TELEMETRY_DEVELOPMENT
      - TELEMETRY_STAGING
      - TELEMETRY_PRODUCTION
  - name: BuildConfiguration
    displayName: BuildConfiguration to be used
    default: "Release"
    values:
      - Release
      - Debug

trigger: none
name: $(date:yyyyMMdd)$(rev:.r)

jobs:
  - job: Build
    strategy:
      matrix:
        win-x64-sf:
          TelemetryType: TELEMETRY_DEVELOPMENT
          BuildConfiguration: "Release"
          BuildPlatform: "win-x64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/windows/amd64/kubectl.exe"
          KubectlPath: "win"
          KubectlFileName: "kubectl.exe"
          ZipFilePathName: "win"
          ZipFileName: "lpk-win.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
        win-arm64-sf:
          TelemetryType: TELEMETRY_DEVELOPMENT
          BuildConfiguration: "Release"
          BuildPlatform: "win-arm64"
          SelfContained: true
          KubectlDownloadUrl: "https://dl.k8s.io/release/v1.27.3/bin/windows/arm64/kubectl.exe"
          KubectlPath: "win"
          KubectlFileName: "kubectl.exe"
          ZipFilePathName: "win"
          ZipFileName: "lpk-win.zip"
          poolName: "VSEngSS-MicroBuild2022-1ES"
    pool:
      name: $(poolName)
      demands:
        - msbuild
        - visualstudio
        - DotNetFramework
      vmImage: $(vmImage)
    steps:
      - template: templates/build.yml
        parameters:
          TelemetryType: $(TelemetryType)
          BuildConfiguration: $(BuildConfiguration)
          BuildPlatform: $(BuildPlatform)
          SelfContained: $(SelfContained)
          KubectlDownloadUrl: $(KubectlDownloadUrl)
          KubectlPath: $(KubectlPath)
          KubectlFileName: $(KubectlFileName)
          ZipFilePathName: $(ZipFilePathName)
          ZipFileName: $(ZipFileName)
      - template: templates/generate-lks.yml
