version: 0.1
env:
    - name: FOO
      value: stats-api-testing
    - name: STATS_API_VOLUME_PATH
      value: $(volumeMounts:kube-api-*)
    - name: STATS_API_CONFIG_PATH
      value: $(volumeMounts:config)