name: integration tests for B2K
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: create minikube cluster and deploy todo-app
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    # - name: Build image
    #  run: |
    #   export SHELL=/bin/bash
    #   eval $(minikube -p minikube docker-env)
    #   docker build -f ./Dockerfile -t local/example .
    #    echo -n "verifying images:"
    #   docker images 
    - name: create todo-app namespace
      run: kubectl create namespace todo-app
    - name: Deploy todo-app
      run:
        kubectl apply -f https://raw.githubusercontent.com/Azure/Bridge-To-Kubernetes/main/samples/todo-app/deployment.yaml -n todo-app
    - name: Wait for pods to be ready
      run: |
        kubectl wait --for=condition=ready pod --all -n todo-app --timeout=300s
        kubectl get pods -n todo-app
    # - name: Test service URLs
    #   run: |
    #     echo "starting minikube tunnel"
    #     minikube tunnel  > /dev/null 2>&1 & tunnelPID=$!
    #     sleep 60
    #     url=$(kubectl get services -n todo-app -o json | jq '.items[] | select(.metadata.name == "frontend").status.loadBalancer.ingress[0].ip')
    #     echo "service url is: $url"
    #     curl -m 3 $url:80
    #     kill $tunnelPID
    - name: Install and Run B2K
      timeout-minutes: 10
      run: |
          echo "installing B2K"
          curl -fsSL https://raw.githubusercontent.com/Azure/Bridge-To-Kubernetes/main/scripts/install.sh | bash
          echo "validating B2K"
          dsc connect --help
          echo "starting B2K..."
          dsc connect --service stats-api --namespace todo-app --local-port 3001 --control-port 51424 --use-kubernetes-service-environment-variables > /dev/null & b2kPID=$!
          echo "b2kPID: $b2kPID"
          ps -efo PID,STAT,TIME,START | grep "$b2kPID"
          echo "sleeping for 60 seconds..."
          sleep 60
          echo "start local stats-api project"
          cd samples/todo-app/stats-api
          npm install
          npm run start
          echo "validating if b2k debugging is working for stats-api in todo-app namespace"
          curl http://127.0.0.1/api/stats -H 'Content-Type: application/json; charset=utf-8'
          kill $b2kPID
          echo "validating if b2k is disconnected successfully"
          restorepodexists=kubectl get pod -n todo -o json | jq '.items[] | select(.metadata.name | contains("restore"))'
          if [ -z "$restorepodexists" ]; then
            echo "restore pod does not exist"
            exit 0
          else
            echo "restore pod exists"
            exit 1
          fi


