name: integration tests for B2K
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: create minikube cluster and deploy todo-app
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    # - name: Build image
    #  run: |
    #   export SHELL=/bin/bash
    #   eval $(minikube -p minikube docker-env)
    #   docker build -f ./Dockerfile -t local/example .
    #    echo -n "verifying images:"
    #   docker images 
    - name: create todo-app namespace
      run: kubectl create namespace todo-app
    - name: Deploy todo-app
      run:
        kubectl apply -f https://raw.githubusercontent.com/Azure/Bridge-To-Kubernetes/main/samples/todo-app/deployment.yaml -n todo-app
    - name: Test service URLs
      run: |
        minikube service list -n todo-app
        minikube service stats-api -n todo-app --url
        echo "------------------opening the service------------------"
        curl $(minikube service stats-api -n todo-app --url)        
